mysql:
    datasource:
        readSize: 2  #读库个数
        type: com.alibaba.druid.pool.DruidDataSource
        mapperLocations: classpath:/com/ddtong/core/dao/mapper/*.xml,/com/ddtong/core/dao/mapper/*/*.xml
        configLocation: classpath:/mybatis-config.xml
        write:
           url: jdbc:mysql://120.78.172.114:3306/ddt?useUnicode=true&amp;characterEncoding=utf-8
           username: system
           password: 29RTqsHY5JyNnSb0
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 1
           maxActive: 3
           initialSize: 2
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
        read01:
           url: jdbc:mysql://120.78.172.114:3306/ddt?useUnicode=true&amp;characterEncoding=utf-8
           username: system
           password: 29RTqsHY5JyNnSb0
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 1
           maxActive: 3
           initialSize: 2
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
        read02:
           url: jdbc:mysql://120.78.172.114:3306/ddt?useUnicode=true&amp;characterEncoding=utf-8
           username: system
           password: 29RTqsHY5JyNnSb0
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 1
           maxActive: 3
           initialSize: 2
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat  